# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xci
# IP: The module: 'sistema_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xci
# IP: The module: 'sistema_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_processing_system7_0_0/sistema_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
