# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0.xci
# IP: The module: 'sistema_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0.xci
# IP: The module: 'sistema_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lgomez/Documentos/MAGISTER_UBA/Bimestre06/MyS_FPGA/laboratorios/TF_ALU_1005A/sistema_ALU/sistema_ALU.srcs/sources_1/bd/sistema/ip/sistema_rst_ps7_0_100M_0/sistema_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
